services:
  cosmos-server:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    hostname: yacht
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /:/mnt/host
      - /var/lib/yacht:/config
    network_mode: bridge
    ports:
      - "8000:8000"
